### ISSUE TITLE
Latest release of docker compose is known to cause problems with JeroenBoersma/docker-compose-development

### ISSUE THREAD

**Issue by peterschriever** [elgentos/setup#32]
Today during installation of my laptop Jerke and I encountered some problems getting the JeroenBoersma/docker-compose-development docker containers to work. This was most likely caused by a v2+ version of docker-compose. We have since gotten those docker containers to work by installing docker compose v1.29.2

Instead of `releases/latest` we should probably manually specify the latest v1 release.

**Comment by johmanx10** [comment]
Can you elaborate on the specific problems you encounter with the development environment? I feel those issues have to be solved there and only here should we influence the version if it seems like it cannot be solved in a timely manner.

**Comment by peterschriever** [comment]
The ssl and web containers are exiting soon after or on `dev up`; `dev ps` output
```
development-ssl-1               "/docker-entrypoint.…"   ssl                 exited (1)          
development-web-1               "/docker-entrypoint.…"   web                 exited (1)          
```

mysql command doesnt work;
```
➜  magento2 mysql                                                      
ERROR 2005 (HY000): Unknown MySQL server host 'db' (2)
```

After running `magerun2 env:create` (succesfully) my `bin/magento` commands throw the following errors at the bottom;
```
In Abstract.php line 144:
                                                                                             
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not   
  known                                                                                      
                                                                                             

In Abstract.php line 128:
                                                                                             
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not   
  known                                                                                      
                                                                                             

In Abstract.php line 128:
                                                                                             
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known                                                                                         
```

I have tried using `dev logs tail web -f` to see what happens when running `dev up`
```
➜  magento2 dev logs tail web -f 
development-web-1  | 2021/10/14 08:13:04 [emerg] 1#1: host not found in upstream "fpm:9000" in /etc/nginx/backends.conf:2
development-web-1  | nginx: [emerg] host not found in upstream "fpm:9000" in /etc/nginx/backends.conf:2
```

Going back to 1.29.1 instantly fixes these problems.

**Comment by JeroenBoersma** [comment]
`docker compose v2.x` works entirely different than the current `1.x`

I've it running locally, need to update the docs and do some more testing...
Will push to a new branch so you can test too.
